### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by darkphan** [Yuudaari/soulus#1]
Soulus Version: 1.0.0-b768f53
Forge: 14.23.1.2577
Minecraft: 1.12.2

When starting up on a server the following crash happens: https://pste.me/#/PAek6

**Comment by Yuudaari** [comment]
Oh dang I knew I was forgetting something, I forgot to test it works on a server... will fix asap hah

**Comment by darkphan** [comment]
Thanks!

**Comment by Yuudaari** [comment]
Fixed with [v1.0.1](https://github.com/Yuudaari/soulus/releases/tag/v1.0.1). Thanks again!
