### ISSUE TITLE
Crash on load - Waila Compat

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#10]
Soulus Version: Soulus-1.12.2-1.4.0-045b66c
Forge Version: 14.23.1.2581

Here is the crash log:
https://gist.github.com/Dragnier/bd2b0aefae35ed15f05c1a4466145010

**Comment by Yuudaari** [comment]
I swear I tested this... oh well. Thanks for the report

**Comment by Yuudaari** [comment]
Fixed with [v1.4.1](https://github.com/Yuudaari/soulus/releases/tag/v1.4.1)
