### ISSUE TITLE
Crash when summoner gets exploded

### ISSUE THREAD

**Issue by darkphan** [Yuudaari/soulus#14]
In some testing, I had built a wither near a summoner (with upgrades) and when the wither exploded it crashed the game with the following crashlog: https://pste.me/#/YveVN

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crash when summoner is exploded](https://trello.com/c/1yl4T7M2/102-crash-when-summoner-is-exploded)

**Comment by Yuudaari** [comment]
Closed with [1.6.0](https://github.com/Yuudaari/soulus/releases/tag/v1.6.0)
