### ISSUE TITLE
Add Ore Dictionary to bones

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#18]
Some recipes, especially mod added ones, occasionally require bones; but they don't work with your new replacement. Might be fixed for some recipes with an ore dictionary entry, but I'm not sure because some recipes don't play nice with ore dictionary. May be worth specifying inside the mod itself rather than leaving it to pack devs.

**Comment by Yuudaari** [comment]
Thanks, I forgot about this one. The next update will be kind of delayed, hopefully that's not too much of an issue. The next version will be likely be 2.0 unless there's bad bugs. Some big new stuff =)

**Comment by Yuudaari** [comment]
Fixed by [v2.0.0](https://github.com/Yuudaari/soulus/releases/tag/v2.0.0)
