### ISSUE TITLE
Scales don't turn into Scale Chunks

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#19]
Scale to scale chunk recipe doesn't work. Tried putting them in the crafting grid, both player and crafting table, with no luck.

**Comment by Yuudaari** [comment]
Somehow I missed this recipe.... will be part of 2.0 (hopefully ready in the next week)

**Comment by Yuudaari** [comment]
Fixed by [v2.0.0](https://github.com/Yuudaari/soulus/releases/tag/v2.0.0)
