### ISSUE TITLE
How to add Modded Mobs?

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#2]
Is the config capable of handling the addition of mobs from other mods? If so, how would I go about adding the Thermal Suite mobs to the config? If not, are there any plans to add this capability?

**Comment by Yuudaari** [comment]
They are potentially already supported, but I haven't tested yet. It may not work perfectly yet. If it does happen to work, this is what you'll need to add to the soulus.json:

```
drops.<the kind of bone type you want your mob to be in>.<the ResourceLocation of your mob>.drop_chance = a number, will be loaded as a float but you can provide whatever

souls.<the ResourceLocation of your mob>.quantity = an int, should be the amount of essence required to craft a soulbook of this mob
```

If it works correctly that should be all you need, but, again, I haven't tested with it yet (have been more focused on minimum viable product... and I failed cause it doesn't work for dedicated servers currently, hah)

If you try it out let me know how it goes, any errors, etc!

**Comment by Dragnier** [comment]
I tested this with the Cyberzombie from the unofficial port of Cyberware and definitely get essence, though the name is a bit wierd in the tooltip. item.soulus:essence.cyberware:cyberzombie.name is what the essence is named instead of Cyberzombie Essence.

Using craft tweaker, it shows up as <soulus:essence>.withTag({essence_type: "cyberware:cyberzombie"})

I wonder if there is a way to extract the mob name from the nbt data, capitalize it, and then have the essence name itself accordingly?

**Comment by Yuudaari** [comment]
I can't return string names for all cases, for items I have to return translation ids. That's why currently the blocks and items all look like that. You will have to add in translations via a resourcepack.

**Comment by Dragnier** [comment]
How does the new essence config work? I mean, adding new modded mobs is pretty straight forward as is changing current entries. But what about for dropping the same essence from multiple bone types? For example, I want to add a small chance of enderman essence to the normal bones of 1% or less... does that need a whole new entry or can I just add normal bone type to the existing entry somehow without removing the ender bone type?

**Comment by Yuudaari** [comment]
it requires a new entry but fair warning: it may cause unexpected things to happen. It’s not really a supported thing.

**Comment by Yuudaari** [comment]
Closing this issue because the comments in here have outdated information. See #12
