### ISSUE TITLE
How to enable mob drops

### ISSUE THREAD

**Issue by accessdenied0** [Yuudaari/soulus#20]
Hey @Yuudaari, 

First of all I want to point out that the part in your readme under summoner > _config.replace_spawners_with_summoners_ is outdated. You changed this method to a more flexible option. I hope that helps you.

Secondly I run sadly again in a problem, where I don't get standard or vanilla drops from any kind of mob.
I deleted and reloaded the Soulus.json and did nothing change, except change the summoner replacement option ( "summoner_replacer": {},) 
and enabled the mobs (https://pastebin.com/YwMYA5Bh).

I mainly enabled the summoner for the Extra-Utilities Summoner to convert. (crafting)
Did I something wrong? And if this isn't intended: How to fix it or how can I help you?

This wouldn't be the last time I did something wrong but maybe this time it is a issue,

thankful,

access_denied

**Comment by Yuudaari** [comment]
See the same config docs: https://github.com/Yuudaari/soulus/blob/master/docs/CONFIG.md#configcreatures-

They have been updated since a recent version. Let me know if there's anything you don't understand in this readme.

**Comment by accessdenied0** [comment]
Yeah,
I did not change the drop list. I changed the mobs to spawn twice as frequently, but I didn't change the whitelist, means all drops are whilelisted ("whitelisted_drops": ["*"],). But Zombies doesn't drop flesh, Ghast no Ghast-tears, Blazes no Blazerods. 

I have used a TiC Sword with Looting III and a normal Sword to confirm. Both didn't drop their proper drops or these from Reliqary. 
Extra Utilities Drops, Terraqueous and AA-Solidified Experience still drops.

**Comment by Yuudaari** [comment]
You can't increase the spawn rate of the base game, spawn chance only works to reduce the frequency.

I just realised you sent the relevant part of the config:
```json
   "*": {
                    "spawn_chance": 2.0,
                    "drops": {
                        "summoned": {
                            "whitelisted_drops": [
                                "*"
                            ],
                            "blacklisted_drops": []
                        }
                    }
                }
```
you're only whitelisting all drops from summoned creatures, you have to change "summoned" to "all"

**Comment by accessdenied0** [comment]
Ok. But why is it pre-generated, that way? Like I said, I didn't change much...

**Comment by Yuudaari** [comment]
The configs are all based around the way that soulus is designed. The two main ways to play with soulus are:
1. No natural spawns
2. No natural mob drops

Allowing natural mob drops and spawns makes soulus a lot easier. However, I understand that people will want to play the game that way, that's why the configs support it.

**Comment by accessdenied0** [comment]
Last thing like mentioned the config config.replace_spawners_with_summoners is now "summoner_replacer": {}, in your config. This piece of information is a bit outdated. you can change the mode apparently because it is in normal.

**Comment by Yuudaari** [comment]
Yep, I just forgot about that. Thanks for the reminder =)

**Comment by accessdenied0** [comment]
I thank you a lot again. Your mod let open a lot possibilities! I like it, but I can get confusing sometimes. I'm sorry about that. The last thing I need is to add specific drops to mobs, like Iron or Silver-nuggets to Silverfishes, lol.
