### ISSUE TITLE
Crash when removing entries from essences.json

### ISSUE THREAD

**Issue by Thyriel** [Yuudaari/soulus#22]
Removing some entries from essences.json (so those mobs are not affected / spawnable by your mod and the corresponding essences are no longer obtainable by chunks) results in crash when the removed essences where previously in an inventory and the client then tries to render these essence items. (Parrot essence in that case)

Crashlog: https://pastebin.com/vTTFCPuD
essences.json: https://pastebin.com/bm4sMnKu  (edit > if you want to test that config, either remove the mmm:spider_zombie entry or install mutated mobs mod)

Items that are removed from a mod (even due to config changes) should be removed from a savegame on load too (Minecraft normally informs you on loading that items are no longer present and if you want to remove them. In that case it didn't asked). Not sure if that fully applies here as it seems that it's NBT tags no longer able to render, but at least it shouldn't crash and render a savegame unuseable because of a config change). Maybe would work just giving it a default texture to render when none has been found/configured.

**Comment by Yuudaari** [comment]
This is a bug, missing essences should appear as "unfocused essence". Will fix asap.

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixed a crash when rendering nonexistent essences](https://trello.com/c/MEtCxzXc/171-fixed-a-crash-when-rendering-nonexistent-essences)

**Comment by Yuudaari** [comment]
Fixed as of [v2.5.0](https://github.com/Yuudaari/soulus/releases/tag/v2.5.0)
