### ISSUE TITLE
Config profile to disable vein generation

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#29]
I might've missed this, but would it also be possible to add a profile to disable vein generation as well? I tried to disable it manually by setting the min and max sizes to 0.0 and chance to zero and got the following crash. Can save headaches for people like me who don't know too much about the argument bounds.

https://hastebin.com/fefipiyomu.sql

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Added profiles for fossil veins to enable/disable them easier. Moved Summoner Replacement and Veins into the world/ directory.](https://trello.com/c/s7CtjLCB/199-added-profiles-for-fossil-veins-to-enable-disable-them-easier-moved-summoner-replacement-and-veins-into-the-world-directory)

**Comment by Yuudaari** [comment]
Fixed as of [v3.2.0](https://github.com/Yuudaari/soulus/releases/tag/v3.2.0)
