### ISSUE TITLE
Support dimension white/blacklisting

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#3]
Is there any way you could make the disabling of all spawns configurable by dimension? Basically I only want to disable natural spawns in the Overworld and Nether, not every other dimension. This is especially necessary for certain mods like Aether Legacy or Twilight Forest since they rely heavily on spawns to work properly and in the End for the Dragon fight.

**Comment by Yuudaari** [comment]
Sure, I'll add that to my todo.

**Comment by Yuudaari** [comment]
I should add this to the readme, but you can currently whitelist certain mobs or blacklist certain mobs:

```
{
  "spawn_entity_whitelist": [ "minecraft:sheep" ]
}
```
This makes it so that only sheep can spawn.

```
{
  "spawn_entity_blacklist": [ "minecraft:sheep" ]
}
```
This makes it so that everything *except* sheep can spawn.

This probably supports most of what you want to do, but I'll still add in your suggestion at some point.

**Comment by Dragnier** [comment]
Does that support wildcards? Could I use:

**Comment by Yuudaari** [comment]
It doesn't currently support wildcards, but that's another great idea! I'm going to open a separate issue for that.

**Comment by Yuudaari** [comment]
After my planned changes to this the config file will look like this:

```
{
	"no_mob_spawning": {
		"*": {
			"*": {
				"*": {
					"spawn_chance": 0.0
				}
			}
		},
		"end": {
			"*": {
				"minecraft:ender_dragon": {
					"spawn_chance": 1.0
				} 
			}
		}
	}
}
```
What you're looking at is `no_mob_spawning.<dimension>.<biome>.<mob>`.
This specific example would disable all spawns except for the ender dragon, but only when the ender dragon is in the end... more explicit names are used over less explicit, so `minecraft:ender_dragon` > `minecraft:*` > `*`

**Comment by Yuudaari** [comment]
Supported as of [v1.1.0](https://github.com/Yuudaari/soulus/releases/tag/v1.1.0)
