### ISSUE TITLE
[1.12.2] Crash on server start

### ISSUE THREAD

**Issue by kwpugh** [Yuudaari/soulus#34]
Report: https://gist.github.com/kwpugh/c28bccff3190394784c1a4c798eb0b8c

Mod: Soulus-1.12.2-3.2.0-bd70217.jar
Forge: forge-1.12.2-14.23.2.2611-installer.jar

I deleted the existing configs.

**Comment by Yuudaari** [comment]
Fixed as of [v3.2.1](https://github.com/Yuudaari/soulus/releases/tag/v3.2.1)

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixed crash when config files were missing](https://trello.com/c/IzUH5b0l/209-fixed-crash-when-config-files-were-missing)
