### ISSUE TITLE
[1.12.2] NPE from latest update (v.3.2.0)

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#35]
https://hastebin.com/vupekuhera.sql

**Comment by Yuudaari** [comment]
Fixed as of [v3.2.1](https://github.com/Yuudaari/soulus/releases/tag/v3.2.1)

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixed crash when config files were missing](https://trello.com/c/IzUH5b0l/209-fixed-crash-when-config-files-were-missing)
