### ISSUE TITLE
Slime in default config

### ISSUE THREAD

**Issue by Thyriel** [Yuudaari/soulus#36]
Not a big thing but i just realized that minecraft:slime is missing in the essences configuration but as these don't naturally spawn and slimeballs are pretty much essential for crafting i wondered if this is intended ?

**Comment by Yuudaari** [comment]
It is intended. I haven’t thought of a good way to get their essence yet. Same with iron golems. It doesn’t make sense to me to have them drop bones. At some point I’ll think of something. It’s not high up on my todo tho

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Slime and Iron Golem essence in Composer](https://trello.com/c/qoRH7ClA/212-create-slime-and-iron-golem-essence-in-composer)

**Comment by Yuudaari** [comment]
Added in [v3.3.0](https://github.com/Yuudaari/soulus/releases/tag/v3.3.0)

**Comment by Thyriel** [comment]
Pretty interesting way to get them via glue when they don't spawn naturally ;)
