### ISSUE TITLE
[Soulus 3.3.1] Summoners still replacing spawners in the Twilight Forest

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#41]
replacement.json = https://hastebin.com/zeninagifi.json
replacement#disabled.json = https://hastebin.com/usiwijayuz.json

![2018-02-12_22 30 09](https://user-images.githubusercontent.com/26587049/36132439-51328a94-1045-11e8-97fb-ddcd625badd3.png)

![2018-02-12_22 30 19](https://user-images.githubusercontent.com/26587049/36132443-540bcffa-1045-11e8-870b-8d3fb5afa16f.png)

The spawners from Doomlike Dungeons appear just fine (can't confirm with Strongholds, I have them disabled in my pack). Both of these screesnots were taken from Hollow Hills (second summoner is a Kobold summoner, not sure why it says Empty) and I ran into a Helmet Crab Summoner in the Goblin Stronghold.

**Comment by Yuudaari** [comment]
Are the files correct? You have replacement.json linking to an empty file `{}` and replacement#disabled.json linking to what should be the main file `{ "profile": "disabled" }`

**Comment by Yuudaari** [comment]
I can't repro on my end. What is the path of your files? Cause they were moved previously to `world/summoner_replacement`

**Comment by Vyraal1** [comment]
Ah yeah I confused the copying and pasting of the links - replacement#disabled.json is the one with empty brackets and replacement.json has `{ "profile": "disabled" }`, I can confirm that, it was only a copy and paste error posting the issue.

![image](https://user-images.githubusercontent.com/26587049/36132785-33b7aa24-1047-11e8-8834-d78834b4e244.png)

This is the directory of my config files. The weird issue is that the spawners in other dimensions seem fine, the ones in Doomlike Dungeons are back to regular spawners.
![2018-02-12_22 51 47](https://user-images.githubusercontent.com/26587049/36132816-59703830-1047-11e8-8407-42b77c1ebd56.png)

**Comment by Yuudaari** [comment]
Again, it's `world/summoner_replacement/replacement.json`, not `summoner_replacement/replacement.json`. They were moved, 3.3 I think?

**Comment by Vyraal1** [comment]
I'm bad at reading. Reaaalllllly bad at reading. Thanks again for your help!

**Comment by Yuudaari** [comment]
No problem, hah. I don't think the configs will be moving around again for a while, since the mod is stablising now for the most part. For future reorganising there may be save conversion.
