### ISSUE TITLE
Unable to override fossil textures since version 3.3.0

### ISSUE THREAD

**Issue by darkphan** [Yuudaari/soulus#42]
Using Resource Loader to override the fossil textures no longer works from version 3.3.0

**Comment by Yuudaari** [comment]
The textures were moved. The fossil textures are the same names, but located in the `fossils/` subfolder now. Full path: `assets/soulus/textures/blocks/fossil/*.png`

**Comment by Yuudaari** [comment]
Closing as no further explanation was given. Feel free to comment or open a new issue if this is not resolved.
