### ISSUE TITLE
No bone drops from some creatures on default config

### ISSUE THREAD

**Issue by MaxTheBreaker** [Yuudaari/soulus#45]
Soulus-1.12.2-3.4.1-5180932
Entities like endermite, pig or zombie are not dropping bones. 
Skeleton archer is dropping normal bones.
If I assign vanilla bones to be dropped from pig via custom loot tables, normal bone drops are coming back.

When I install Soulus-1.12.2-3.4.0-a39bafc version, bone drops from endermite, zombie and pig are normal.

**Comment by Yuudaari** [comment]
Fixed as of [v3.4.2](https://github.com/Yuudaari/soulus/releases/tag/v3.4.2)
