### ISSUE TITLE
The zombie book is pink for some reason

### ISSUE THREAD

**Issue by Yuudaari** [Yuudaari/soulus#46]
Not the essence tho, the essence is fine

**Comment by CJL48** [comment]
I'm seeing this too. At least in my case, a zombie soulbook that has less than 8 or so essence in it is the 'correct' color (matches zombie essence), but once it's been filled to a certain point, it changes colors to pink.

**Comment by Yuudaari** [comment]
Fixed as of [v4.0.0](https://github.com/Yuudaari/soulus/releases/tag/v4.0.0)
