### ISSUE TITLE
Allow specifying custom bones types

### ISSUE THREAD

**Issue by YaibaToKen** [Yuudaari/soulus#47]
Would it be feasible to generate custom fossils, bones and bone chunks in a similar way to how the essences are generated? Fossil world generation would then be configured the same way the normal fossils are. An entry could be added for each fossil missing from the world gen files.

This would allow for better customisation of the mod to suit modpacks' and players' ideals further.
For example, in the modpack I'm making, I would love if I could make a bone type for cybernetically enhanced mobs (robotic parts and rewired) and another one for evolved mobs (galacticraft).

This could also be used for mutated mobs (there are several mods that add those) and so on.

**Comment by Yuudaari** [comment]
**Fossil blocks**: Use ContentTweaker. It might have a way to generate them, if it doesn't, Soulus does ([`world/veins/veins.json`](https://github.com/Yuudaari/soulus/blob/master/docs/CONFIG.md#worldveinsveinsjson-)).

**Bones**: Use ContentTweaker. ContentTweaker may also have a way of changing mob drops, if it doesn't I'm pretty sure there's another mod somewhere that does have this capability. (Dropt might, not sure if that's only block drops)

**Bone Chunks**: Use ContentTweaker. ContentTweaker probably has a way of making these drop from your fossil blocks. I would guess it also has a method you can attach on right click, so you can give yourself essences from it. If it doesn't, you could make crafting recipes for the bone chunk + something else related to the mob in question to make the essence, maybe?

You can already add custom essences, so the previous stuff should be all you need. 

In the future, Soulus will allow specifying new bone types. It will take a bone type id (used in place of the base ids such as "normal", "fungal", etc), a Bone item id, and a Bone Chunk item id. You'll still have to make the items with another mod like ContentTweaker. In the `essences.json` you'll be able to specify your id in place of the base bone type. It will add the right click action to use the bone chunk and get essences automatically, and the `loot` section will use your configured bone as well.

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bone types are now configurable.](https://trello.com/c/SOunmIhK/240-bone-types-are-now-configurable)

**Comment by Yuudaari** [comment]
Implemented as of [v4.0.0](https://github.com/Yuudaari/soulus/releases/tag/v4.0.0)
