### ISSUE TITLE
Readme doesn't mention all skewer upgrades

### ISSUE THREAD

**Issue by CJL48** [Yuudaari/soulus#49]
On the Soulus curseforge page, you say:
> It also can be upgraded to tether ender creatures, to have increased damage, to poison creatures, and has a very expensive player upgrade (the previously mentioned soul catalyst).
However, the wiki/readme only mentions one upgrade (other than loading an unfinished blood gem to automatically fill it), that being quartz for increased damage. Poison, tethering, and the 'player upgrade' are not mentioned at all. I'm pretty sure that spider eyes are the poison upgrade, but I don't know what the item you use for ender tethering (ender pearl/eye/bone?) is, or what the 'player upgrade' does (causes mobs to drop xp and player drops, I guess). This information should probably be part of the documentation of the mod.

**Comment by Yuudaari** [comment]
Thanks, I'll add them as soon as I can. For the time being:

https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/block/skewer/Skewer.java#L52-L57

You are correct about the player upgrade.

FYI, the items show up in the WAILA & TOP tooltips as well, it is *highly recommended* to use one of these mods with Soulus.

**Comment by CJL48** [comment]
Thank you. I didn't know about WAILA/TOP, I'll add one of those.
