### ISSUE TITLE
Sky Resources 2 compatibility?

### ISSUE THREAD

**Issue by SimonMeskens** [Yuudaari/soulus#50]
I was trying to make a pack with Sky Resources 2 and Soulus, but Soulus requires iron to get started and Sky Resources only unlocks that pretty late. Meanwhile, gunpowder is an early resource in Sky Resources. It's all a bit of a catch 22. Do you have an idea on how to tweak recipes?

**Comment by Yuudaari** [comment]
From an initial glance, it seems like it's kinda like ex nihilo but more magicky, if they allow you to tweak their recipes maybe make one that produces an ender-iron dust blend. Then you can get into soulus summoners without actually getting real iron

You could also just turn off the mob spawning cancelation & mob drop cancelation features, and just use soulus for the tech

Besides that, I don't have any experience with Sky Resources 2 and I don't have the time to look into how it works. As the modpack creator, changing the recipes to something that is compatible with all included mods is on you
