### ISSUE TITLE
Fossils in ice blocks, for ice biomes

### ISSUE THREAD

**Issue by YaibaToKen** [Yuudaari/soulus#51]
As the name implies, I hereby suggest a fossil block variant (like the sand, gravel and dirt ones) for ice based biomes. 
I can assist by PRing the code, though I'll need help with the block textures / model.

**Comment by Yuudaari** [comment]
This already exists, it's the "frozen fossil"

**Comment by Yuudaari** [comment]
Oh, are you saying an ice block with a fossil inside it?

**Comment by YaibaToKen** [comment]
Yes, exactly that :) (sorry, didn't realize I wasn't being specific enough)

**Comment by Yuudaari** [comment]
At some point I'm planning on working on this mod again, but I'm not sure when. In the past few months I've been really busy with work and other projects, I'm not sure when I'm going to have the free time again that I had when I was first working on Soulus. When I do have that time again I'm not even sure I'm going to continue on this version of Soulus. I was sorta thinking maybe a Soulus 2 when I have time, post 1.13? And I'd like to make it using my mod Fabricate instead, which to this point is stuck very early in development. 

If you feel like submitting a PR for this, feel free, even w/o the textures/models if you like. I'm willing to include it. I'm not sure when I'll get to adding the textures, testing, and releasing tho.

**Comment by YaibaToKen** [comment]
I can't help with the textures/models, but I'll try to get a PR ready for the rest :)

**Comment by Yuudaari** [comment]
Ice fossils are rejected due to the inability to make their appearance better. It does not appear to be possible to cull their faces when they are around other ice blocks, so their sides will always be visible. Apologies for moving this to Help Wanted and it being rejected anyway.

**Comment by YaibaToKen** [comment]
No problem :)
