### ISSUE TITLE
Config to Disable Recipe Registry Loading for Composer

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#55]
Creating a large modpack with the FTB Team and I wanted to ask about if there is a config to prevent the Composer from being an autocrafter for all 3x3 recipes, and only a specialty crafter for the CT integration. In a pack with thousands of recipes, would there be a noticeable loading time increase to register all of the recipes again for the Composer? If so, I would just like to prevent that.

**Comment by Yuudaari** [comment]
The composer does not re-register recipes, it just uses the basic 3x3 recipe registry to tell if a recipe is valid. It appears as its own recipes in JEI due to the way that the composer support for JEI functions.

**Comment by Vyraal1** [comment]
Ah perfect then, so its only a cosmetic issue.
