### ISSUE TITLE
[Config Help] How to enable vanilla spawning

### ISSUE THREAD

**Issue by TimGoll** [Yuudaari/soulus#56]
I'd like to integrate your mod into my modpack but I also want vanilla spawning and normal vanilla drop behaviour. I think I got how to edit the file to get the latter, but I'm not quite sure how to get normal spawning.
It would be cool if you'd include a default "vanilla" config file.

A small note to your readme: There isn't animania under your supported mobs, but it seems like animania mobs work perfectly fine with your mod

**Comment by YaibaToKen** [comment]
It's all in the README but here's the specific location:
https://github.com/Yuudaari/soulus/blob/master/docs/CONFIG.md#creaturescreaturesjson-

Please close this if your issue is solved by it as that would mean less work for Yuudaari

**Comment by Yuudaari** [comment]
All you'll need to do is change your config profile to "yes_creatures_yes_drops", see the link posted by YaibaToKen for more information on the relevant config file and the section above to learn about config profiles.

**Comment by TimGoll** [comment]
Thank you, I think I've understand how it works!
I haven't seen this README, Only the main README
