### ISSUE TITLE
[Minor] Niobium is missing oreDict Entry as ingotNiobium

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#58]
Bit minor as not many mods really use that metal, but GregTech: Community Edition does, and overall just better for other mod integration if desired.

**Comment by Yuudaari** [comment]
Niobium is one of the last endgame things in Soulus, and it's not true Niobium. It's a metal forged from souls, so it's nicknamed after Niobe (Greek story about woman losing her entire family to the gods and being real sad). I believe this might also be the root from Niobium irl.

Regardless, the metals aren't the same, and I highly suspect that if I marked them as the same, it would completely unbalance soulus and make  the soulus endgame trivial. (No need for a good composer setup to get there)

If you like, you can add the ore dictionary with crafttweaker tho.
