### ISSUE TITLE
Ex Nihilo: Creatio Sieve Recipes not registering.

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#6]
I have loaded with Ex Nihilo set both to use external JSON registry and not to use them. Neither way shows any sieve results regarding Soulus.

For now, I'll add them manually. Thought you'd want to know though.

**Comment by Yuudaari** [comment]
Oh, I forgot to make an issue for this, thanks for the reminder

**Comment by Yuudaari** [comment]
Fixed with [v1.1.1](https://github.com/Yuudaari/soulus/releases/tag/v1.1.1)
