### ISSUE TITLE
Crash with Astral Sorcery Shooting Star

### ISSUE THREAD

**Issue by pupnewfster** [Yuudaari/soulus#60]
I was AFK on my test world (thought I had already closed MC), but when I went to close it I noticed my single player world had crashed.

https://paste.dimdev.org/equniyipud.mccrash

Soulus: 4.0
Astral Sorcery: 1.10.9
Forge: 14.23.5.2796

**Comment by Yuudaari** [comment]
Fixed as of [v4.0.1](https://github.com/Yuudaari/soulus/releases/tag/v4.0.1)
