### ISSUE TITLE
Marrowing is completely broken in the default config

### ISSUE THREAD

**Issue by donqixot** [Yuudaari/soulus#61]
I am trying latest version Soulus-1.12.2-4.0.1-0769b4c with nothing else installed. When I right click with normal bone chunks, I hear sound and chunk count goes down, but no essence is given and after a while, when I open chest inventory, all bone chunks are given back to me.

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixed marrowing.](https://trello.com/c/vmFnXkre/282-fixed-marrowing)

**Comment by Yuudaari** [comment]
Fixed as of [v4.0.2](https://github.com/Yuudaari/soulus/releases/tag/v4.0.2)

**Comment by donqixot** [comment]
Thank you!
