### ISSUE TITLE
Crash - MP Server

### ISSUE THREAD

**Issue by KAfable** [Yuudaari/soulus#62]
Sorry, trying to get more information atm, just happened minutes ago on a multiplayer server.

https://gist.github.com/Vyraal1/c50f697d2d866130f92a8b45d73c8039

**Comment by Vyraal1** [comment]
Actually this wasn't on latest yet - we'll try to replicate on the latest.

**Comment by Yuudaari** [comment]
Yes, this should be fixed on 4.0.1
