### ISSUE TITLE
Default for Hunting Dimension

### ISSUE THREAD

**Issue by wizard1399** [Yuudaari/soulus#64]
Could you add a default config for when the Hunting Dimension mod is installed? Basically, it would need to allow all spawns in the hunting dim. 

BTW, the hunting dim and your mod make a great modpack pairing.

**Comment by Yuudaari** [comment]
Sorry, I'm probably not going to write configs for specific mods, because it would be too much work to maintain and for not much benefit. If anyone else decides to write any, though, I can put them on the website.

Thanks for playing!
