### ISSUE TITLE
Crash on creation of default configs

### ISSUE THREAD

**Issue by Vyraal1** [Yuudaari/soulus#66]
https://gist.github.com/Vyraal1/6738e180c75d68e621806bdc11c4550f

Was curious to see what new configs would be added with the latest update, removing the configs folder and letting it regenerate ended up with this.

**Comment by Vyraal1** [comment]
Just as a heads up, this also crashes on a fresh instance with just JEI, Crafttweaker and minimal mods.

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixed a crash when creating default configs.](https://trello.com/c/7ZBe6og4/304-fixed-a-crash-when-creating-default-configs)

**Comment by Yuudaari** [comment]
Fixed as of [v4.1.1](https://github.com/Yuudaari/soulus/releases/tag/v4.1.1)
