### ISSUE TITLE
JEI Support for Custom Recipe Types

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#7]
The basic Bone chunk has no recipe. Dry, Mossy, etc. are all fine. But the basic one isn't there.

**Comment by Yuudaari** [comment]
I can't reproduce the recipe not existing, but JEI doesn't show the recipe. Don't know why.
![image](https://user-images.githubusercontent.com/6081834/34185476-27a3bd68-e4eb-11e7-8169-c0d9217f658a.png)

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace normal bones with a mod-added bone](https://trello.com/c/XGKsV0eE/94-replace-normal-bones-with-a-mod-added-bone)

**Comment by Yuudaari** [comment]
Closed with [v1.7.0](https://github.com/Yuudaari/soulus/releases/tag/v1.7.0)
