### ISSUE TITLE
Question: MC spawners

### ISSUE THREAD

**Issue by wizard1399** [Yuudaari/soulus#71]
In terms of the configs, are mobs that are spawned from the vanilla Minecraft spawner considered "spawn" or "summoned"? 

Basically, I am trying to find a way that allows spawning from dungeon spawners, but disables spawning in the rest of the dimension for hostile creatures.

**Comment by Yuudaari** [comment]
Any spawns that happen from sources other than the Summoner are not considered "summoned", and a vanilla spawner is not a Summoner. The reason there are only the two possible sources is there's no real way for me to detect the source of a spawn.

It may be helpful to note that the vanilla spawners in the overworld are replaced by Summoners by default. You can configure this functionality in the `summoner_replacement.json` config, and additionally replace spawners in other dimensions/biomes/structures with Summoners.

A note: Summoners have some limitations that normal spawners don't, they're restricted by mob type, and don't save NBT. So for example, if a vanilla spawner had a zombie with armour, the summoner replacement would just make it a zombie summoner.

**Comment by wizard1399** [comment]
Darn, guess I will have to set it up for yes mobs yes drops and use the mod In control to do the nitty gritty work for me.
