### ISSUE TITLE
[Bug] Soulus mod prevents you from sleeping in a bed

### ISSUE THREAD

**Issue by MushWolf** [Yuudaari/soulus#73]
Version: soulus-1.12.2.4.2.9-d3cdd94.jar
forge version: forge-14.23.5.2825

Soulus somehow prevents you from sleeping in a bed (tested it without any other mods and the issue persists). As soon as you right click a bed with an empty hand you get the vanilla message 'you need to wait till nighttime to use a bed' (or whatever the message is again).

Log (although it doesn't say anything as far as I can see):
[latest.log](https://github.com/Yuudaari/soulus/files/3073291/latest.log)

**Comment by Yuudaari** [comment]
Fixed as of [v4.2.1](https://github.com/Yuudaari/soulus/releases/tag/v4.2.1) (the file has already been approved on CurseForge as well)
