### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by wizard1399** [Yuudaari/soulus#75]
Hey, 

I am having trouble with config that I am writing. I have put it through a format checker and found it to be good syntax so it must be something else going on.

[skyblock_with_hunting_dim](https://pastebin.com/WSXKUUua)

Could you take a look? Everytime I load it, I find another version in the folder with .err.json at the end.

**Comment by Yuudaari** [comment]
The ".err.json" file is outputted when Soulus has to "correct" the JSON file, basically it means that there's something different about the format or something between your version and the one Soulus outputs — this can happen if properties are missing, if values aren't the same kind, etc.

It seems like in this case the error was that you weren't providing the "has_xp" property, so it was added automatically to each creature configuration that was missing it. I recommend keeping an eye on the log when doing config work, as you'll see info about any errors in the configs.

**Comment by wizard1399** [comment]
Thanks for the tip. I will try adding that to the entries that are missing it and report back.

**Comment by wizard1399** [comment]
Could you update the wiki to show what entries are required. I filled the examples from the wiki and it seemed like has_xp was optional.

**Comment by Yuudaari** [comment]
Well, most things are optional, in a way — when you load the configs they'll just be set to defaults and an `.err.json` will be made.

But yea, I'll try to remember to update the examples on the site sometime soon

**Comment by Yuudaari** [comment]
I've updated the site to include the `"has_xp"` property in its examples. I think this issue has been solved, but if it hasn't just leave another comment and let me know. Thanks for playing with Soulus!
