### ISSUE TITLE
[Crash] Using an empty soulbook on a Summoner

### ISSUE THREAD

**Issue by al132mc** [Yuudaari/soulus#79]
There's no good reason that you'd want to use an empty soul book on a Summoner, but several of my users have reported to me that if you do this it will cause a crash. I was able to easily replicate this behavior on my own. Here's a [crash log](https://pastebin.com/iz4efxig)

**Comment by Yuudaari** [comment]
I can't believe I never noticed this one. I'm on vacation right now so I can't fix it, but I have a couple questions in the meantime, if you feel like answering:

1. What is the value of `soulbookEssenceRequiredToInsert` in your `block/summoner.json` config?
    - If it's `0`, you can increase it in order to prevent empty Soulbooks from being inserted — the range is `0.0` (0%) to `1.0` (100%)
    - If you're always able to insert it no matter what you set this value to, it looks like this check is what's broken
2. When you say an empty Soulbook, do you mean a Soulbook you just grab out of the creative inventory, or do you mean one that has been used up by a Summoner?
    - I don't remember ATM if there's a difference. In case there is, this might just help me resolve the problem a little faster when I get back

**Comment by al132mc** [comment]
Sorry it took me so long to respond, I mean soulbook with no mob type, as in a soulbook that has never had a mob type. When you craft a soulbook it will not have a mob type until you craft it with essence. I am referring to this book prior to crafting it with essence.

**Comment by Yuudaari** [comment]
I actually got back a couple days ago and forgot about this, so thanks for the ping. New build should be up shortly
