### ISSUE TITLE
Soulus crashes MC when loaded without Ex Nihilo now

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#8]
I decided to make a skyblock that actually didn't use Ex Nihilo because the recipes weren't there and now that they are it crashed trying to load MC before even reaching the main menu.

Crash log: https://gist.github.com/Dragnier/4d663f6817d481e16f8f2dab4db2d630

Had to revert all the way back to 1.1.0 to get it to load.

**Comment by Yuudaari** [comment]
Well dang it! Sorry about that, hah

**Comment by Yuudaari** [comment]
Fixed with [v1.2.1](https://github.com/Yuudaari/soulus/releases/tag/v1.2.1)
