### ISSUE TITLE
Normal style Summoner recipe & Ender style Endersteel Bars recipe are identical

### ISSUE THREAD

**Issue by TheAwesomeM2** [Yuudaari/soulus#81]
how does this supposed to work either you nned to update patchouli for more information
because im not sureif it works like this 
![Untitled](https://user-images.githubusercontent.com/29637816/60929132-5d040880-a2b0-11e9-85d5-0b2e3d601e40.png)

**Comment by TheAwesomeM2** [comment]
its a bug or something because i need to create the normal one

**Comment by Yuudaari** [comment]
.....hahahahhahahaha i can't believe I never noticed this, nice catch. I'll get a fix up soon. In the meantime, you can make one of another style, then use one more ender dust to change it back to a normal style. Note that the different styles only affect the appearance and which potion effects the creatures spawn with, so there's nothing really keeping you from using one summoner over another (unless, like, you're in a modpack that requires exclusively a normal summoner as a recipe ingredient)
