### ISSUE TITLE
Missing metal oredicts

### ISSUE THREAD

**Issue by Lykrast** [Yuudaari/soulus#82]
The following items/blocks are not oredicted properly:

* Endersteel Ingot (should be like `ingotEndersteel`)
* Endersteel Shard (should be like `nuggetEndersteel`)
* Ender-Iron Dust Blend (should be like `dustEnderSteel`)
* Block of Endersteel (`blockEndersteel`)
* Dark Endersteel Ingot (`ingotDarkEndersteel` or `ingotEndersteelBlack`, as you want)
* Dark Endersteel Shard (`nuggetDarkEndersteel` or `nuggetEndersteelBlack`)
* Ash-Ender-Iron Dust Blend (`dustDarkEndersteel` or `dustEndersteelBlack`)
* Block of Dark Endersteel (`blockDarkEndersteel` or `blockEndersteelBlack`)
* Same with Nobium I think you get the idea

This would allow most tech mods to properly process those ingots with things like crushers or compressors. Since you can already turn them back to dust with the Sledgehammer and the other crafts can be done by hand this wouldn't pose any balance issue.

**Comment by Yuudaari** [comment]
I don't intend to Ore Dict these by default because that makes them functionally the same as the items from other mods that use the same names. That makes the Soulus tech tree basically pointless.

Note that Soulus's metals working with other mod crushers/compressors is definitely a good thing, but I don't think it's worth Soulus's tech tree basically being "ruined by default" when in the presence of another mod.

If you want to apply these Ore Dicts, I recommend using CraftTweaker.

**Comment by Lykrast** [comment]
The thing is that I know no other mod that adds Endersteel (Ender IO is End Steel, so not the same), Dark Endersteel or Nobium ingots, and I find it unlikely that another mod will in the future.

That means in practice the Soulus tech tree will remain as the only way to get those ingots in the first place (disregarding CraftTweaker shenanigans), so there is no issue there.

Personally I did the same for Prodigy Tech for Ferramic and Zorrasteel. No other mod add those materials so there was no issue there either.

**Comment by Yuudaari** [comment]
I believe GregTech has Niobium #58 

I can add those ore dicts, but it would only be with an option and it would be disabled by default.

**Comment by Lykrast** [comment]
There is an alternative, you could oredict your Niobium as `ingotSoulNiobium` (or `ingotSoulusNiobium` or something similar), as it's not "true" Niobium but made of souls as you said.

This way, no GregTech cheese, and the oredict can be on by default.

**Comment by Yuudaari** [comment]
That's a good idea. I'll do that then. 👍
