### ISSUE TITLE
Roguelike Dungeons spawners are only rarely replaced

### ISSUE THREAD

**Issue by LycanBlackpaw** [Yuudaari/soulus#85]
So I'm in the process of making a small adventure pack (Betweenlands, Aether, Roguelike Dungeons, etc) and decided to throw in this mod to make things a bit more interesting. However, I've run into a problem: Soulus doesn't replace the spawners in Roguelike dungeons with summoners, so the entire dungeon is completely devoid of enemies despite spawners being everywhere.

The Roguelike config is rather sparse, and the only config option there doesn't seem to do anything, so I was wondering if you could help me figure out a way to configure your mod to convert them?

EDIT: Looked around a bit more and apparently I'm half-wrong. _Some_ spawners do convert, but not all, and I have no idea why.

**Comment by Yuudaari** [comment]
I'm not sure why only some Summoners convert. I'll take a look. There *could* be a check that only replaces spawners if Soulus would put a Summoner there that works the same, but I don't know if I actually did something like that.

**Comment by LycanBlackpaw** [comment]
The only help I can offer is that the one spawner that converted was a single skeleton spawner. Over three worlds for testing, none of the other spawners changed, and I don't know exactly why that one did.

Could it have something to do with the custom NBT strings? Roguelike spawners give randomized armor and weapons to the mobs in question

**Comment by Yuudaari** [comment]
Okay so to be honest I'm not sure why that one skeleton spawner managed to convert. 

It seems like the problem with Roguelike Dungeons is that the generation it uses is not structure generation — and the way it does it, there's no way I can run code on the chunks afterwards. I have added a thing that will replace mob spawners as players are near them instead, and this should take care of all edge cases like this mod.
