### ISSUE TITLE
Doc: "down is to the left of the composer block" isn't helpful.

### ISSUE THREAD

**Issue by WazWaz** [Yuudaari/soulus#89]
Without knowing which way it's "facing", the "left" of the composer block doesn't mean anything. The visualization is rotating, so that's no clue.

Should probably be "down/right [whichever is true] is the side with the composer block".

(mod version 0.10.77)

**Comment by Yuudaari** [comment]
In case you didn't figure it out, the right side of the grid is where the composer is.

**Comment by WazWaz** [comment]
(fortunately the recipes in the modpack I was playing are all donuts, so orientation didn't matter)
