### ISSUE TITLE
[Suggestion] Summoner Limited Uses -> Reverts to Empty

### ISSUE THREAD

**Issue by Dragnier** [Yuudaari/soulus#9]
I wonder if it would be possible to have a config option to turn on summoner limited uses and configure those uses per soulbook type? Once the uses were run out, the summoner would revert to empty and return an empty soulbook if right clicked or broken.

In addition, perhaps there could be an upgrade of some kind that used harder to obtain materials to craft which would allow a soul book combined with it to become infinite uses.

**Comment by Yuudaari** [comment]
This is a cool idea, thanks!

**Comment by Yuudaari** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make summoners use up soulbooks over time](https://trello.com/c/RY90GcCG/93-make-summoners-use-up-soulbooks-over-time)

**Comment by Yuudaari** [comment]
Closed with [v1.7.0](https://github.com/Yuudaari/soulus/releases/tag/v1.7.0)
