### ISSUE TITLE
It crashes when I try to break dirt with fossils

### ISSUE THREAD

**Issue by Figon** [Yuudaari/soulus#91]

**Comment by Yuudaari** [comment]
Oh yeah I should note you'll need to delete your `config/soulus/misc/fossil_block_bone_chunk_drops.json` file to regenerate it, it's invalid. It won't crash anymore even if it stays broken, but without regenerating it you won't get bone drops

**Comment by Figon** [comment]
Erm sorry for asking but where is that?

**Comment by Figon** [comment]
Thanks!

**Comment by Figon** [comment]
Quick question, what does regenerate mean?

**Comment by Yuudaari** [comment]
Like, the file will be re-created by the mod if it's deleted.
