### ISSUE TITLE
Game crash when summoner spawn.

### ISSUE THREAD

**Issue by immortalmice** [Yuudaari/soulus#94]
I'm playing a mod pack with this mod, and I find a problem in the code.
In the line 494 of yuudaari.soulus.common.block.summoner.SummonerTileEntity.java, spawn function.

> final String[] spawnNames = CONFIG_ESSENCES.get(essenceType).spawnNames;

It trying to get the name of the essence.
So I go to read yuudaari.soulus.common.config.essence.ConfigEssences where CONFIG_ESSENCES come from.

In line 85

> return essences.stream().filter(config -> config.essence.equalsIgnoreCase(type)).findFirst().orElse(null);

So the problem happend when it can't find matched data, so it will return null.
But at line 494 of SummonerTileEntity.java, it will try to get "spawnNames" property in a null pointer.
Then caused NullPointerException and game crash.

Check the return value of "get" function first before get spawnNames property will be much better. 

thx.

**Comment by Yuudaari** [comment]
Please share your log

**Comment by immortalmice** [comment]
> Description: Ticking block entity

> java.lang.NullPointerException: Ticking block entity
> at yuudaari.soulus.common.block.summoner.SummonerTileEntity.spawn(SummonerTileEntity.java:494)
> at yuudaari.soulus.common.block.summoner.SummonerTileEntity.func_73660_a(SummonerTileEntity.java:334)
> at net.minecraft.world.World.func_72939_s(World.java:1838)
> at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> at java.lang.Thread.run(Thread.java:745)

[crash-2019-12-03_05.06.37-server.txt](https://github.com/Yuudaari/soulus/files/3933945/crash-2019-12-03_05.06.37-server.txt)
I found that I can't upload json file here, so link is below
https://mega.nz/#!qAlwESiI!Bds5ihOaNmu9NROWrM0ek0k9Mf-6L20PmRQewUwRePU

**Comment by Yuudaari** [comment]
Thank you! Will take a look when I’m at PC
